name: Build Kstuff with the Latest Payload SDK

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: true

jobs:
  payload-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install build-essential clang-18 lld-18 xxd yasm nasm

    - name: Get Latest SDK Release Info
      id: sdk-release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const release = await github.rest.repos.getLatestRelease({
            owner: 'LightningMods',
            repo: 'etaHEN-SDK'
          });
          core.setOutput('download_url', release.data.assets.find(asset => asset.name.endsWith('.zip')).browser_download_url);

    - name: Download Latest SDK
      run: |
        curl -L "${{ steps.sdk-release.outputs.download_url }}" -o ps5-sdk.zip
        mkdir -p ${{ runner.tool_cache }}/ps5-payload-sdk
        unzip ps5-sdk.zip -d ${{ runner.tool_cache }}/ps5-payload-sdk
        echo PS5_PAYLOAD_SDK=${{ runner.tool_cache }}/ps5-payload-sdk/ps5-payload-sdk >> $GITHUB_ENV
        chmod 0777 -R ${{ runner.tool_cache }}/ps5-payload-sdk/ps5-payload-sdk 

    - name: Build Payload
      run: |
        export PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk
        bash ci-ps5-kstuff-ldr.sh

    - name: Upload Payload
      uses: actions/upload-artifact@v4
      with:
        name: Payload
        path: ./ps5-kstuff-ldr/kstuff.elf
        if-no-files-found: error
